### ISSUE TITLE
ASP.Net Identity v2.1

### ISSUE THREAD

**Issue by thepatrick** [danielwertheim/mycouch.aspnet.identity#1]
Do you have any plans for updating this to match ASP.Net Identity v2.1?

**Comment by danielwertheim** [comment]
Yes, but when updating it for v2.0.0 I found issues with how stuff was validated in the Identity core. Basically, not working 100% (feature wize) unless data store allows secondary unique indices.

Will try and get around to update to v2.1 and see if there's a good "fix" for the other part.

**Comment by mpaul31** [comment]
is this project still active? just trying to figure out whether or not to utilize

thx!

**Comment by danielwertheim** [comment]
The code just committed in `develop` branch is updated to work with latest release of Asp.Net Identity. Look in `IdentityConfig.cs` in the `Samples.Mvc5` of how to configure, since e.g. a custom `UserIdentityValidator` had to be hooked in to enforce unique email (which also is the Id and Username), since CouchDB only has one unque field (the `_id`).

Feel free to try it out. If found satisfying I will put it out as a NuGet.

**Comment by danielwertheim** [comment]
@mpaul31 Any luck trying it out?

**Comment by mpaul31** [comment]
Yes it works great! My users have asked for unique email and username functionality so not sure yet if I can use this yet. Is this possible?

**Comment by danielwertheim** [comment]
Well, if the custom validator works as expexted, it should. I guess you
will have to try it.

**Comment by mpaul31** [comment]
Ah ok I thought u mentioned above you could only support one unique field. Will try it out

**Comment by danielwertheim** [comment]
I miss understood. Yes. One unique field only. Hence _id and UserName
points to Email.
